feat: squash feature branch next
* added the target path to the schema command
* added search engine as virtual module
* added css selectors in outline numbering
* added url preview in the search box
* added node pagefind search
* added data-noindex for no index
* updated react and vite dependencies
* creation of yarn workspaces
* added eslint to verify import
* interact dir is now called node
* added a searchbox component in the header
* pagefind plugin added
* added HTML cache
* refactor: markdown is now async
* added standalone support (ie without node_modules)
* added offcanvas in holy layout
* fix: missing favicon
* added file tree in aside

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -9,16 +9,12 @@ tasks:
     cmds:
       # prepare/check before a release
       - |
-        # check typescript
-        echo "Check typescript"
-        yarn check
-        # check peer-dependencies rules
-        echo "Check peer"
-        npx check-peer-dependencies no
-        # https://yarnpkg.com/migration/pnp#calling-the-doctor
-        echo "Check undeclared dependency"
-        yarn dlx @yarnpkg/doctor
+
   deploy:
     cmds:
       - |
-        yarn check && git tag -f early-access && git push -f origin early-access
+        if [ ! -z "$(git status --porcelain)" ]; then
+          echo "Could not deploy, change has been made (repo is dirty)"
+          exit 1          
+        fi
+        yarn workspace @combostrap/interact check && git tag -f early-access && git push -f origin early-access
